import csv
import ipaddress
import json
import re


# Maximum amount of detail to put into the Security Onion
# ip-descriptions.csv Description field.
MAX_DESCRIPTION_LENGTH = 220

# Don't let service discovery overwhelm the asset identity.
MAX_HOSTNAMES = 2
MAX_SERVICES = 4


def clean_text(value):
    if value is None:
        return ""

    return str(value).strip()


def add_unique(parts, value):
    """
    Add a non-empty value once, using case-insensitive comparison.
    """
    value = clean_text(value)

    if not value:
        return

    existing = {
        item.lower()
        for item in parts
    }

    if value.lower() not in existing:
        parts.append(value)


def is_ip_literal(value):
    """
    Returns True when value is an IPv4/IPv6 address.
    """
    value = clean_text(value)

    if not value:
        return False

    # Strip possible brackets around IPv6.
    value = value.strip("[]")

    try:
        ipaddress.ip_address(value)
        return True
    except ValueError:
        return False


def looks_like_ip_port(value):
    """
    Filters values like:
        192.168.50.48:8060
        192.168.50.1:8443
    """
    value = clean_text(value)

    if not value:
        return False

    match = re.fullmatch(
        r"(\d{1,3}(?:\.\d{1,3}){3}):(\d+)",
        value
    )

    if not match:
        return False

    try:
        ipaddress.ip_address(match.group(1))
        return True
    except ValueError:
        return False


def useful_hostname(hostname):
    """
    Determine whether an observed hostname is useful as an
    asset identity.

    Keeps:
        homeassistant.local
        nicos-macbook-air.local
        netbox.local
        bedroom-tv
        workstation01.example.local

    Rejects:
        _googlecast._tcp.local
        _companion-link._tcp.local
        _services._dns-sd._udp.local
        192.168.50.48
        192.168.50.48:8060
    """
    hostname = clean_text(hostname).rstrip(".")

    if not hostname:
        return False

    lower = hostname.lower()

    if is_ip_literal(hostname):
        return False

    if looks_like_ip_port(hostname):
        return False

    # DNS-SD / Bonjour / mDNS service records.
    if hostname.startswith("_"):
        return False

    service_patterns = (
        "._tcp.",
        "._udp.",
        "_dns-sd.",
        "_services.",
        "_googlecast.",
        "_rdlink.",
        "_companion-link.",
        "_androidtvremote",
    )

    if any(
        pattern in lower
        for pattern in service_patterns
    ):
        return False

    # Some observed names are actually URLs/paths.
    if "://" in hostname:
        return False

    return True


def hostname_score(hostname):
    """
    Rank observed hostnames.

    Higher number = preferred.
    """
    hostname = clean_text(hostname).rstrip(".")

    if not useful_hostname(hostname):
        return -1

    score = 0

    lower = hostname.lower()

    # FQDN/local hostname is generally better than a bare token.
    if "." in hostname:
        score += 20

    if lower.endswith(".local"):
        score += 10

    # Human-readable names tend to be more useful.
    if "-" in hostname:
        score += 3

    # Avoid prioritizing extremely long autogenerated identifiers.
    if len(hostname) <= 40:
        score += 5

    if len(hostname) > 80:
        score -= 20

    return score


def select_best_hostnames(hostnames):
    """
    Filter, deduplicate, rank and limit observed hostnames.
    """
    unique = {}

    for hostname in hostnames or []:
        hostname = clean_text(
            hostname
        ).rstrip(".")

        if not useful_hostname(hostname):
            continue

        key = hostname.lower()

        if key not in unique:
            unique[key] = hostname

    ranked = sorted(
        unique.values(),
        key=lambda value: (
            hostname_score(value),
            -len(value)
        ),
        reverse=True
    )

    return ranked[:MAX_HOSTNAMES]


def normalize_service(service):
    """
    Normalize a discovered service string.
    """
    service = clean_text(service)

    if not service:
        return ""

    # Collapse weird whitespace.
    service = " ".join(
        service.split()
    )

    return service


def select_services(services):
    """
    Deduplicate and limit observed services.
    """
    results = []

    seen = set()

    for service in services or []:
        service = normalize_service(
            service
        )

        if not service:
            continue

        key = service.lower()

        if key in seen:
            continue

        seen.add(key)
        results.append(service)

    return results[:MAX_SERVICES]


def parse_discovery_comments(comments):
    """
    Extract NetBox/ORB discovery information from the
    IP Address comments field.

    Returns:
        hostnames: list[str]
        services: list[str]
    """

    hostnames = []
    services = []

    if not comments:
        return hostnames, services

    text = clean_text(comments)

    #
    # First try normal JSON.
    #
    try:
        data = json.loads(text)

        discovered_hostnames = (
            data.get("hostnames")
            or []
        )

        if isinstance(
            discovered_hostnames,
            str
        ):
            discovered_hostnames = [
                discovered_hostnames
            ]

        for hostname in discovered_hostnames:
            hostname = clean_text(
                hostname
            ).rstrip(".")

            if hostname:
                hostnames.append(
                    hostname
                )

        ports = (
            data.get("ports")
            or []
        )

        if isinstance(ports, list):

            for port in ports:

                if not isinstance(
                    port,
                    dict
                ):
                    continue

                state = clean_text(
                    port.get("state")
                ).lower()

                if (
                    state
                    and state != "open"
                ):
                    continue

                number = port.get(
                    "number"
                )

                protocol = (
                    clean_text(
                        port.get(
                            "protocol"
                        )
                    )
                    or "tcp"
                )

                service = clean_text(
                    port.get("service")
                )

                if not number:
                    continue

                if service:
                    value = (
                        f"{service} "
                        f"{number}/{protocol}"
                    )
                else:
                    value = (
                        f"{number}/{protocol}"
                    )

                services.append(
                    value
                )

        return (
            hostnames,
            services
        )

    except (
        json.JSONDecodeError,
        TypeError
    ):
        pass

    #
    # Fallback for escaped JSON-ish strings.
    #
    hostname_matches = re.findall(
        r'"hostnames"\s*:\s*\[(.*?)\]',
        text,
        flags=re.IGNORECASE
    )

    for block in hostname_matches:

        for hostname in re.findall(
            r'"([^"]+)"',
            block
        ):
            hostname = (
                hostname
                .strip()
                .rstrip(".")
            )

            if hostname:
                hostnames.append(
                    hostname
                )

    port_pattern = re.compile(
        r'"number"\s*:\s*(\d+).*?'
        r'"protocol"\s*:\s*"([^"]+)".*?'
        r'"service"\s*:\s*"([^"]*)".*?'
        r'"state"\s*:\s*"open"',
        flags=(
            re.IGNORECASE
            | re.DOTALL
        )
    )

    for (
        number,
        protocol,
        service
    ) in port_pattern.findall(text):

        protocol = (
            protocol.strip()
            or "tcp"
        )

        service = service.strip()

        if service:
            services.append(
                f"{service} "
                f"{number}/{protocol}"
            )
        else:
            services.append(
                f"{number}/{protocol}"
            )

    return (
        hostnames,
        services
    )


def get_assigned_name(record):
    """
    Extract a physical Device or Virtual Machine name
    from the NetBox IP assigned object.
    """

    assigned = record.get(
        "assigned_object"
    )

    if not isinstance(
        assigned,
        dict
    ):
        return ""

    #
    # Physical Device Interface
    #
    device = assigned.get(
        "device"
    )

    if isinstance(
        device,
        dict
    ):

        name = (
            device.get("name")
            or device.get("display")
        )

        if name:
            return clean_text(
                name
            )

    #
    # Virtual Machine Interface
    #
    virtual_machine = assigned.get(
        "virtual_machine"
    )

    if isinstance(
        virtual_machine,
        dict
    ):

        name = (
            virtual_machine.get(
                "name"
            )
            or virtual_machine.get(
                "display"
            )
        )

        if name:
            return clean_text(
                name
            )

    return ""


def format_mac(mac):
    mac = clean_text(
        mac
    ).lower()

    if not mac:
        return ""

    return f"MAC {mac}"


def build_description(
    record,
    observation=None
):
    """
    Build the Security Onion IP description.

    Identity priority:

      1. NetBox Device / VM name
      2. NetBox DNS name
      3. NetBox description
      4. NetBox Discovery hostname
      5. Security Onion passive hostname
      6. Security Onion MAC
      7. Passive / active services

    NetBox identity always takes priority over observed identity.
    """

    observation = (
        observation
        or {}
    )

    identity_parts = []
    context_parts = []

    #
    # -------------------------------------------------
    # Authoritative NetBox identity
    # -------------------------------------------------
    #

    assigned_name = get_assigned_name(
        record
    )

    add_unique(
        identity_parts,
        assigned_name
    )

    dns_name = clean_text(
        record.get("dns_name")
    ).rstrip(".")

    if useful_hostname(
        dns_name
    ):
        add_unique(
            identity_parts,
            dns_name
        )

    description = clean_text(
        record.get(
            "description"
        )
    )

    add_unique(
        identity_parts,
        description
    )

    #
    # -------------------------------------------------
    # NetBox / ORB observations
    # -------------------------------------------------
    #

    nb_hostnames, nb_services = (
        parse_discovery_comments(
            record.get("comments")
        )
    )

    for hostname in select_best_hostnames(
        nb_hostnames
    ):
        add_unique(
            identity_parts,
            hostname
        )

    #
    # -------------------------------------------------
    # Security Onion passive observations
    # -------------------------------------------------
    #

    so_hostnames = (
        observation.get(
            "hostnames",
            []
        )
        or []
    )

    for hostname in select_best_hostnames(
        so_hostnames
    ):
        add_unique(
            identity_parts,
            hostname
        )

    #
    # MAC address
    #
    so_macs = (
        observation.get(
            "macs",
            []
        )
        or []
    )

    if so_macs:
        add_unique(
            context_parts,
            format_mac(
                so_macs[0]
            )
        )

    #
    # -------------------------------------------------
    # Services
    # -------------------------------------------------
    #

    so_services = (
        observation.get(
            "services",
            []
        )
        or []
    )

    combined_services = (
        list(so_services)
        + list(nb_services)
    )

    for service in select_services(
        combined_services
    ):
        add_unique(
            context_parts,
            service
        )

    #
    # -------------------------------------------------
    # Fallback
    # -------------------------------------------------
    #

    if not identity_parts:
        identity_parts.append(
            "NetBox managed asset"
        )

    #
    # Identity first; observations second.
    #
    all_parts = (
        identity_parts
        + context_parts
    )

    result = " | ".join(
        all_parts
    )

    return result[
        :MAX_DESCRIPTION_LENGTH
    ]


def generate_mapping_file(
    records,
    output_file,
    observations=None
):
    """
    Generate Security Onion:

        /nsm/custom-mappings/ip-descriptions.csv

    from:

        NetBox IP Address records
          +
        Security Onion passive observations.
    """

    observations = (
        observations
        or {}
    )

    mappings = {}

    for record in records:

        address = record.get(
            "address"
        )

        if not address:
            continue

        try:
            ip = str(
                ipaddress.ip_interface(
                    address
                ).ip
            )

        except ValueError:
            continue

        observation = (
            observations.get(
                ip,
                {}
            )
        )

        description = (
            build_description(
                record,
                observation
            )
        )

        mappings[ip] = (
            description
        )

    #
    # Sort actual IP numbers, not strings.
    #
    sorted_ips = sorted(
        mappings,
        key=ipaddress.ip_address
    )

    with open(
        output_file,
        "w",
        newline="",
        encoding="utf-8"
    ) as f:

        writer = csv.writer(
            f
        )

        writer.writerow([
            "IP",
            "Description"
        ])

        for ip in sorted_ips:

            writer.writerow([
                ip,
                mappings[ip]
            ])

    return len(
        mappings
    )
